# -*- coding: utf-8 -*-
"""new_feature_maps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sq6BKBa5TzI61hDcSFRvuR-P8vVD9VLl

# Experimenting with New Feature Maps

## Setup
"""

import sys
from pathlib import Path
import importlib.util
import io
import re
from contextlib import redirect_stdout

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display
from qiskit import QuantumCircuit

repo_dir = Path.cwd().parent
src_dir = repo_dir / "src"
script_path = src_dir / "DQC1_Clustering.py"

results_dir = repo_dir / "results" / "dqc1_experiments"
results_dir.mkdir(parents=True, exist_ok=True)

spec = importlib.util.spec_from_file_location("dqc1", script_path)
dqc1 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(dqc1)

datasets = [
    "spirals",
    "moons",
    "circles",
    "rings_factor02",
    "anistropic_blobs",
]

dqc1.DATA_NOISE = 0.0
dqc1.RANDOM_STATE = 0

dqc1.INIT_CLUSTERS = 8
dqc1.MIN_CLUSTERS = 3
dqc1.N_INIT = 4
dqc1.REPEATS = 2

dqc1.LAYERS = 1
dqc1.DQC1_COMP_RANK = 8

dqc1.DQC1_EXACT_KERNEL = 1
dqc1.DQC1_EXACT_PURITY = 1

dqc1.DQC1_KERNEL_WORKERS = 1
dqc1.DQC1_PURITY_WORKERS = 1
dqc1.DISABLE_TIMERS = 1

"""## Helper Functions"""

def parse_dqc1_metrics(stdout):
    metrics = {
        "DQC1-pre ARI": None,
        "DQC1-pre NMI": None,
        "DQC1-full ARI": None,
        "DQC1-full NMI": None,
    }

    for line in stdout.splitlines():
        lower = line.lower()

        ari = re.search(r"ARI\s*=\s*(-?\d+\.\d+|-?\d+)", line, re.IGNORECASE)
        nmi = re.search(r"NMI\s*=\s*(-?\d+\.\d+|-?\d+)", line, re.IGNORECASE)

        # Matches: DQC1 (ΔH-only)-moons
        if "dqc1" in lower and "h-only" in lower:
            if ari:
                metrics["DQC1-pre ARI"] = float(ari.group(1))
            if nmi:
                metrics["DQC1-pre NMI"] = float(nmi.group(1))

        # Matches: DQC1-FULL-moons
        elif "dqc1-full" in lower or "dqc1 full" in lower:
            if ari:
                metrics["DQC1-full ARI"] = float(ari.group(1))
            if nmi:
                metrics["DQC1-full NMI"] = float(nmi.group(1))

    return metrics

def run_feature_map_dataset_sweep(feature_map, datasets, n=300, verbose=False):
    rows = []

    old_feature_map = dqc1.FEATURE_MAP
    dqc1.FEATURE_MAP = feature_map.strip().lower()

    try:
        for dataset_name in datasets:
            print(f"[RUNNING] feature_map={feature_map}, dataset={dataset_name}")

            all_sets = dqc1.toy_sets(
                n=n,
                noise=dqc1.DATA_NOISE,
                random_state=dqc1.RANDOM_STATE
            )

            selected = None

            for X, y, name in all_sets:
                if name == dataset_name:
                    selected = (X, y, name)
                    break

            if selected is None:
                available = [name for _, _, name in all_sets]
                raise ValueError(f"Dataset '{dataset_name}' not found. Available: {available}")

            X, y, name = selected
            Xn = dqc1.zero_mean_to_unit_interval(X)

            model = dqc1.DQC1EntropyCluster(
                init_clusters=dqc1.INIT_CLUSTERS,
                n_init_per_seed=dqc1.N_INIT,
                kernel_shots=dqc1.DQC1_KERNEL_SHOTS,
                exact_sv_kernel=bool(dqc1.DQC1_EXACT_KERNEL),
                purity_shots=dqc1.DQC1_PURITY_SHOTS,
                exact_sv_purity=bool(dqc1.DQC1_EXACT_PURITY),
                kernel_workers=dqc1.DQC1_KERNEL_WORKERS,
                purity_workers=dqc1.DQC1_PURITY_WORKERS,
                gpu_ids=None,
                random_state=dqc1.RANDOM_STATE,
                compress_rank=dqc1.DQC1_COMP_RANK,
            )

            buffer = io.StringIO()

            with redirect_stdout(buffer):
                model.fit(X)

                pre_labels = dqc1.labels_from_clusters(X.shape[0], model.clusters_)
                pre_scores = dqc1.eval_scores(Xn, y, pre_labels)

                print(
                    f"    DQC1 (ΔH-only)-{dataset_name} | "
                    f"K={len(model.clusters_):2d}  "
                    f"ARI={pre_scores['ARI']:.3f}  "
                    f"NMI={pre_scores['NMI']:.3f}"
                )

                model.fit_full(X)

                full_labels = model.labels_full_
                full_scores = dqc1.eval_scores(Xn, y, full_labels)

                print(
                    f"  DQC1-FULL-{dataset_name} (K*={model.Kstar_}) | "
                    f"K={model.Kstar_:2d}  "
                    f"ARI={full_scores['ARI']:.3f}  "
                    f"NMI={full_scores['NMI']:.3f}"
                )

            stdout = buffer.getvalue()

            if verbose:
                print(stdout)

            metrics = parse_dqc1_metrics(stdout)

            rows.append({
                "Feature Map": feature_map,
                "Dataset": dataset_name,
                **metrics,
            })

    finally:
        dqc1.FEATURE_MAP = old_feature_map

    return pd.DataFrame(rows)

def plot_feature_map_dataset_sweep(df, feature_map=None, save_path=None):
    plot_df = df.copy()

    if feature_map is None:
        feature_map = plot_df["Feature Map"].iloc[0]

    ax = plot_df.plot(
        x="Dataset",
        y=[
            "DQC1-pre ARI",
            "DQC1-pre NMI",
            "DQC1-full ARI",
            "DQC1-full NMI",
        ],
        kind="bar",
        figsize=(10, 5)
    )

    plt.xlabel("Dataset")
    plt.ylabel("Score")
    plt.title(f"DQC1 Results Across Datasets Using {feature_map} Feature Map")
    plt.ylim(-0.05, 1)
    plt.grid(True, axis="y")
    plt.xticks(rotation=30, ha="right")
    plt.legend()
    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")

    plt.show()

"""## Creating Feature Maps"""

from qiskit import QuantumCircuit

def fm_pauli_xz(x: np.ndarray, layers: int = 1) -> QuantumCircuit:
    x = np.asarray(x, dtype=float)
    n = len(x)
    qc = QuantumCircuit(n, name="U_pauli_xz")
    qc.h(range(n))
    for _ in range(layers):
        for i in range(n):
            qc.rx(2 * np.pi * x[i], i)
            qc.rz(2 * np.pi * x[i] ** 2, i)
        if n >= 2:
            for i in range(n):
                for j in range(i + 1, n):
                    angle = 2 * np.pi * x[i] * x[j]
                    # Implements an X_i Z_j interaction using basis change:
                    # H_i RZZ(i,j) H_i
                    qc.h(i)
                    qc.rzz(angle, i, j)
                    qc.h(i)
    return qc

def fm_iqp(x: np.ndarray, layers: int = 1) -> QuantumCircuit:
    x = np.asarray(x, dtype=float)
    n = len(x)
    qc = QuantumCircuit(n, name="U_iqp")
    for _ in range(layers):
        qc.h(range(n))
        for i in range(n):
            qc.rz(2 * np.pi * x[i], i)
        if n >= 2:
            for i in range(n):
                for j in range(i + 1, n):
                    qc.rzz(2 * np.pi * x[i] * x[j], i, j)
    return qc

def fm_hamiltonian(x: np.ndarray, layers: int = 1) -> QuantumCircuit:
    # This does not explicitly construct H(x).
    # It implements a first-order product formula / Trotter-style evolution
    # under an implicit Hamiltonian:
    # H(x) = sum_i x_i Z_i + sum_i x_i^2 X_i + sum_i x_i*x_{i+1} Z_i Z_{i+1}
    x = np.asarray(x, dtype=float)
    n = len(x)

    qc = QuantumCircuit(n, name="U_hamiltonian")

    for layer in range(layers):
        scale = layer + 1

        # Data-dependent local fields:
        # Z field uses x_i
        # X field uses x_i^2
        for i in range(n):
            qc.rz(2 * np.pi * scale * x[i], i)
            qc.rx(2 * np.pi * scale * x[i] ** 2, i)

        # Data-dependent nearest-neighbor Ising coupling:
        # ZZ term uses x_i * x_{i+1}
        if n >= 2:
            for i in range(n - 1):
                qc.rzz(2 * np.pi * scale * x[i] * x[i + 1], i, i + 1)

    return qc

def fm_random_kitchen_sinks(
    x: np.ndarray,
    layers: int = 1,
    seed: int = 123
) -> QuantumCircuit:
    x = np.asarray(x, dtype=float)
    n = len(x)

    rng = np.random.default_rng(seed)

    # Fixed random parameters for this n and layers
    w_rx = rng.normal(size=(layers, n))
    b_rx = rng.uniform(0, 2 * np.pi, size=(layers, n))

    w_ry = rng.normal(size=(layers, n))
    b_ry = rng.uniform(0, 2 * np.pi, size=(layers, n))

    w_rz = rng.normal(size=(layers, n))
    b_rz = rng.uniform(0, 2 * np.pi, size=(layers, n))

    qc = QuantumCircuit(n, name="U_random_kitchen_sinks")

    for layer in range(layers):
        for i in range(n):
            qc.rx(2 * np.pi * w_rx[layer, i] * x[i] + b_rx[layer, i], i)
            qc.ry(2 * np.pi * w_ry[layer, i] * x[i] + b_ry[layer, i], i)
            qc.rz(2 * np.pi * w_rz[layer, i] * x[i] + b_rz[layer, i], i)

        if n >= 2:
            for i in range(n - 1):
                qc.cx(i, i + 1)

    return qc

def build_feature_map_override(x: np.ndarray, kind: str, layers: int) -> QuantumCircuit:
    k = (kind or "ry").strip().lower()
    if k == "pauli_xz" : return fm_pauli_xz(x, layers)
    if k == "iqp" : return fm_iqp(x, layers)
    if k == "hamiltonian" : return fm_hamiltonian(x, layers)
    if k == "random" : return fm_random_kitchen_sinks(x, layers)
    raise ValueError(f"Unknown feature map: {kind}")

dqc1.build_feature_map = build_feature_map_override

"""### Pauli-XZ Feature Map"""

qc = dqc1.build_feature_map(
    np.array([0.1, -0.2, 0.3, -0.4]),
    "pauli_xz",
    dqc1.LAYERS
)

qc.draw("mpl")

pauli_xz_dataset_df = run_feature_map_dataset_sweep(
    feature_map="pauli_xz",
    datasets=datasets,
    n=300,
    verbose=False
)

display(pauli_xz_dataset_df)

plot_feature_map_dataset_sweep(
    pauli_xz_dataset_df,
    feature_map="pauli_xz",
    save_path=results_dir / "test_Pauli_XZ_dataset_sweep.png"
)

"""### IQP Feature Map"""

qc = dqc1.build_feature_map(
    np.array([0.1, -0.2, 0.3, -0.4]),
    "iqp",
    dqc1.LAYERS
)

qc.draw("mpl")

iqp_dataset_df = run_feature_map_dataset_sweep(
    feature_map="iqp",
    datasets=datasets,
    n=300,
    verbose=False
)

display(iqp_dataset_df)

plot_feature_map_dataset_sweep(
    iqp_dataset_df,
    feature_map="iqp",
    save_path=results_dir / "test_IQP_dataset_sweep.png"
)

"""### Hamiltonian Feature Map"""

qc = dqc1.build_feature_map(
    np.array([0.1, -0.2, 0.3, -0.4]),
    "hamiltonian",
    dqc1.LAYERS
)

qc.draw("mpl")

hamiltonian_dataset_df = run_feature_map_dataset_sweep(
    feature_map="hamiltonian",
    datasets=datasets,
    n=300,
    verbose=False
)

display(hamiltonian_dataset_df)

plot_feature_map_dataset_sweep(
    hamiltonian_dataset_df,
    feature_map="hamiltonian",
    save_path=results_dir / "test_hamiltonian_dataset_sweep.png"
)

"""### Random Kitchen Sinks Feature Map"""

qc = dqc1.build_feature_map(
    np.array([0.1, -0.2, 0.3, -0.4]),
    "random",
    dqc1.LAYERS
)

qc.draw("mpl")

random_dataset_df = run_feature_map_dataset_sweep(
    feature_map="random",
    datasets=datasets,
    n=300,
    verbose=False
)

display(random_dataset_df)

plot_feature_map_dataset_sweep(
    random_dataset_df,
    feature_map="random",
    save_path=results_dir / "test_random_kitchen_sink_dataset_sweep.png"
)